### ISSUE TITLE
gatewaysv2: gatewaysdeposit OP_RETURN inefficiencies

### ISSUE THREAD

**Issue by Alrighttt** [Mixa84/komodo#71]
The format of the OP_RETURNs for gatewaysdeposit transactions could be optimized. 

https://github.com/Mixa84/komodo/blob/de83aa55a41c6cfd7fb07b1473f17fdf50c2a0c1/src/cc/gatewaysV2.cpp#L74

Since we are storing the entire raw hex of the deposit, we should not have to store `cointxid`, `claimvout` or `destpub`(maybe, might require enforcing p2pk-only). 

Since we are also storing the bindtxid, we should not have to store `refcoin` or `publishers`. 

Another clear inefficiency is that `deposithex` is being stored as ASCII-encoded hex and therefore using twice as much space as necessary.

**Comment by Mixa84** [comment]
I agree there could be some optimization of this OP_RETURN.

But some of the data are convenient to be stored there:
- cointxid could be fetched from deposit hex
- claimvout is the vout of the funds that go to multisig address (the term is little bit wrong). It is easier to have vout number which to check in deposit hex than to compare all vouts to see which one goes to multisig address. Also this one uses just 4 bytes, and it could be optimized to 2 or even 1 byte as we won't have more than 2-3 vouts in external deposit tx.
- again easier to have pubkey than to extract it from scriptpubkey, but it could be done. This could save 32 bytes!!!
- refcoin is there to compare with coin from bindtxid. I agree this could be extracted all from bindtxid.
- publishers is interesting parameter in this tx. it is not all the publishers from bind tx, but only those that have the block submitted into oralce. Mostly all nodes will submit block data to oracle, but in situation when some nodes are down it is good to know which nodes submitted data and how much of them to check if consensus of 51% has been reached. I have also been storing txids of those oraclesdata, so I think it is too much duplication and maybe we could just store txids and have the pubkeys from those txids and check everything else.

Regarding deposithex stored as ascii we could probably encode it in let say base58 or etc.

**Comment by Alrighttt** [comment]
Sorry, my explanation of deposit "stored as ASCII-encoded hex" may not have been clear. For example, if we have a transaction hex of 2 bytes, AAAA. We are currently storing this as 4 bytes, 61616161. Hope this clarifies the issue.

**Comment by Mixa84** [comment]
> Sorry, my explanation of deposit "stored as ASCII-encoded hex" may not have been clear. For example, if we have a transaction hex of 2 bytes, AAAA. We are currently storing this as 4 bytes, 61616161. Hope this clarifies the issue.

Ok, you meant to store it as bytes instead of ascii hex representation of bytes. Np.

**Comment by Alrighttt** [comment]
My main concern with the size of this OP_RETURN is that it could result in a deposit that is unable to be claimed because of the transaction size on source chain. We should reduce it as much as possible, but we will likely still need some client-side size checks when the user creates the transaction on source chain. 

For example, if a user intends to deposit BTC to the gateway, if the BTC transaction is too large ( maybe many inputs ), it could result in the gateway being unable to process this deposit. The user would lose their funds.

**Comment by Mixa84** [comment]
Yes, that is a known problem. But basically, we'll optimize deposit tx as much as possible, but if there is a external deposit tx which is greater than 10k bytes then it won't be able to be processed. And that is something users must know before depositing. If there are too many inputs they must consolidate first.

**Comment by Mixa84** [comment]
I will close this issue with following optimizations done:
- cointxid removed as param
- claimvout removed as param, because with rigid validation it can be only at one index - 0
- publishers removed and only txids are stored
- deposithex is stored as bytes of tx

All others are left intact.
